name: Hexlet-Lint
on: [push]
jobs:
  lint-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '15.5'
      - run: make install
      - run: make lint
